
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class=""><a href="<?php echo $this->url('source') ?>"><?php echo $this->translate('Список') ?></a></li>
				<li class=""><a href="<?php echo $this->url('source', array('action'=>'add')) ?>"><?php echo $this->translate('Добавить') ?></a></li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>