<?php

 $title = 'Удалить транзакцию';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Точно нужно удалить <?php echo '#'.$transaction->id ?>
     <?php echo $this->escapeHtml($transaction->source->name); ?> от
     <?php echo $transaction->has('date') ? $transaction->date->format('Y-m-d H:i:s') : ''; ?>?
 </p>
 <?php
 $url = $this->url('trans', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $transaction->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>