<?php

$title = 'Редактирование транзакции';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<script>
	<?php if ($tags) : ?>
	window.tags = <?php echo $tags; ?>;
	<?php endif ?>
</script>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'trans',
	array(
		'action' => 'edit',
		'id'     => $this->id,
	)
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->customRow($form->get('source'));
echo $this->customRow($form->get('amount'));
echo $this->customRow($form->get('date'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();