<?php echo $this->render('application/trans/bits/menu.phtml'); ?>

<table class="table table-bordered">
	<tr>
		<th>ID</th>
		<th>Источник</th>
		<th>Количество</th>
		<th>Дата</th>
	</tr>
	<?php foreach ($this->transactions as $transaction) : ?>
	<tr>
		<td><?php echo $transaction->id; ?>
			<a href="<?php echo $this->url('trans', array('action'=>'delete', 'id'=>$transaction->id)) ?>">
				<span class=" text-right glyphicon glyphicon-trash" aria-hidden="true"></span>
			</a>
		</td>
		<td>
			<a href="<?php echo $this->url('trans', array('action'=>'edit', 'id'=>$transaction->id)) ?>"><?php echo $transaction->source->name; ?></a></br>
		</td>
		<td><?php echo $transaction->amount; ?></td>
		<td><?php echo $transaction->has('date') ? $transaction->date->format('Y-m-d H:i:s') : '' ?></td>
	</tr>
	<?php endforeach; ?>
</table>