<?php

 $title = 'Удалить покупку';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Точно нужно удалить <?php echo '#'.$product->id ?>
     '<?php echo $this->escapeHtml($product->name); ?>' от
     '<?php echo $this->escapeHtml($product->purchase_date); ?>'?
 </p>
 <?php
 $url = $this->url('shopper', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $product->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>