<?php

$title = 'Редактирование покупки';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'shopper',
	array(
		'action' => 'edit',
		'id'     => $this->id,
	)
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->customRow($form->get('name'));
echo $this->customRow($form->get('type'));
echo $this->customRow($form->get('price'));
echo $this->customRow($form->get('amount'));
echo $this->customRow($form->get('purchase_date'));
echo $this->customRow($form->get('start'));
echo $this->customRow($form->get('finish'));
echo $this->customRow($form->get('tags'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();