<?php echo $this->render('application/shopper/bits/menu.phtml'); ?>

<table class="table table-bordered">
	<tr>
		<th>ID</th>
		<th>Наименование</th>
		<th>Цена</th>
		<th>Количество</th>
		<th>Тип</th>
		<th>Дата покупки</th>
		<th>Дата начала</th>
		<th>Дата окончания</th>
	</tr>
	<?php foreach ($this->products as $p) : ?>
	<tr>
		<td><?php echo $p->id; ?>
			<a href="<?php echo $this->url('shopper', array('action'=>'delete', 'id'=>$p->id)) ?>">
				<span class=" text-right glyphicon glyphicon-trash" aria-hidden="true"></span>
			</a>
		</td>
		<td>
			<a href="<?php echo $this->url('shopper', array('action'=>'edit', 'id'=>$p->id)) ?>"><?php echo $p->name; ?></a></br>
			<?php if ( count($p->tags) > 0 )  : ?>
			<p class="alert alert-success">
				<?php foreach ( $p->tags as $tag ) : ?>
					<span class="label label-primary"><?php echo $tag->name ?></span>
				<?php endforeach; ?>
			</p>
			<?php endif; ?>
		</td>
		<td><?php echo $p->price; ?></td>
		<td><?php echo $p->amount; ?></td>
		<td><?php echo $p->type; ?></td>
		<td><?php echo $p->has('purchase_date') ? $p->purchase_date->format('Y-m-d H:i:s') : '' ?></td>
		<td><?php echo $p->has('start') ? $p->start->format('Y-m-d H:i:s') : '' ?></td>
		<td><?php echo $p->has('finish') ? $p->finish->format('Y-m-d H:i:s') : '' ?></td>
	</tr>
	<?php endforeach; ?>
</table>