<?php

 $title = 'Удалить источник';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Точно нужно удалить <?php echo '#'.$source->id ?>
     <?php echo $this->escapeHtml($source->name); ?> от
     <?php echo $source->type ?>?
 </p>
 <?php
 $url = $this->url('source', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $source->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>