<?php

$title = 'Редактирование источник';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<script>
	<?php if ($tags) : ?>
	window.tags = <?php echo $tags; ?>;
	<?php endif ?>
</script>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'source',
	array(
		'action' => 'edit',
		'id'     => $this->id,
	)
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->customRow($form->get('name'));
echo $this->customRow($form->get('type'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();